- package:
  - name: radicle
  - section:
    - name: test:spec
    - message:
      # BEGIN export all for ease of debugging
      - name: Weeds exported
      - module:
        - name: Radicle.Tests
        - identifier:
          - toplevel
          - atom
          - int
          - kw
          - vec
          - parseTest
          - prettyEither
          - stackTraceLines
      # END
  - section:
    - name: test:e2e
    - message:
      - name: Redundant build-depends entry
      - depends:
        # Library is not required, but executable
        - git-remote-ipfs
