- package:
  - name: radicle
  - section:
    - name: test:spec
    - message:
      - name: Redundant build-depends entry
      - depends:
        # Required as compiler plugin
        - tasty-discover
    - message:
      # BEGIN export all for ease of debugging
      - name: Weeds exported
      - module:
        - name: Radicle.Tests
        - identifier:
          - assertReplInteraction
          - atom
          - int
          - kw
          - parseTest
          - prettyEither
          - stackTraceLines
      # END
  - section:
    - name: test:e2e
    - message:
      - name: Redundant build-depends entry
      - depends:
        # Required as compiler plugin
        - tasty-discover
  
