timeout: 3600s # Cache misses are slow to rebuild
steps:
  - id: "Load cache"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      set -euxo pipefail

      source scripts/ci.sh
      load-cache

  - id: "Build deps"
    name: 'haskell:8.6.3'
    env: ['STACK_ROOT=/workspace/.stack']
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      set -euxo pipefail

      stack config set system-ghc --global true
      stack config set install-ghc --global false

      stack build \
        --no-terminal \
        stylish-haskell hlint weeder

      apt-get -qq update
      apt-get -yqq install libpq-dev

      stack build \
        --no-terminal \
        --dependencies-only

  - id: "Save cache"
    waitFor: ["Build deps"]
    name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    env:
    - BRANCH_NAME=$BRANCH_NAME
    args:
    - '-c'
    - |
      set -euxo pipefail

      source scripts/ci.sh
      save-cache

  - id: "Format"
    name: 'haskell:8.6.3'
    env: ['STACK_ROOT=/workspace/.stack']
    args: ['./scripts/check-fmt.sh']

  - id: "Lint"
    name: 'haskell:8.6.3'
    env: ['STACK_ROOT=/workspace/.stack']
    args: ['stack', 'exec', '--', 'hlint', '.']

  - id: "Build"
    name: 'haskell:8.6.3'
    env: ['STACK_ROOT=/workspace/.stack']
    entrypoint: bash
    args:
    - '-c'
    - |
      set -euxo pipefail

      apt-get -qq update
      apt-get -yqq install libpq-dev

      stack build \
        --no-terminal \
        --fast \
        --pedantic \
        --test \
        --no-run-tests

      ./images/radicle-server/ci-copy-bin.sh

  - id: "Test"
    name: 'haskell:8.6.3'
    env: ['STACK_ROOT=/workspace/.stack']
    entrypoint: bash
    args:
    - '-c'
    - |
      set -euxo pipefail

      stack test :doctest
      stack test :spec
      RADPATH="$(pwd)/rad" stack exec -- radicle test/all.rad

  - id: "Lint (weeder)"
    waitFor: ["Build"]
    name: 'haskell:8.6.3'
    env: ["STACK_ROOT=/workspace/.stack"]
    args: ["stack", "exec", "--", "weeder", "--match"]

  - id: "Build reference document"
    waitFor:
    - "Build"
    name: 'haskell:8.6.3'
    env: ['STACK_ROOT=/workspace/.stack']
    entrypoint: bash
    args:
    - '-c'
    - |
      set -euxo pipefail

      mv docs/source/reference.rst oldref
      RADPATH="$(pwd)/rad" stack exec radicle-ref-doc
      if ! (diff oldref docs/source/reference.rst); then
        echo "Reference docs are not checked in"
        exit 1
      fi

  - id: "Check tutorial"
    waitFor:
    - "Build"
    name: 'haskell:8.6.3'
    env: ['STACK_ROOT=/workspace/.stack']
    entrypoint: bash
    args:
    - '-c'
    - |
      set -euxo pipefail

      RADPATH="$(pwd)/rad" stack exec radicle-doc docs/source/guide/Basics.lrad

  - id: "Build radicle-server image"
    waitFor:
    - "Build"
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    env:
    - COMMIT_SHA=$COMMIT_SHA
    - BRANCH_NAME=$BRANCH_NAME
    args:
    - "-c"
    - |
      set -euxo pipefail

      image_name="eu.gcr.io/opensourcecoin/radicle-server"
      short_sha=$(echo "$COMMIT_SHA" | head --bytes=7)
      # Looks like this: b2018.12.06-a76a52f
      tag="b$(date +%Y.%m.%d)-${short_sha}"
      docker build \
        --tag "$image_name" \
        --cache-from "$image_name" \
        ./images/radicle-server

      if [ "$BRANCH_NAME" == "master" ]; then
        image_name="eu.gcr.io/opensourcecoin/radicle-server"
        short_sha=$(echo "$COMMIT_SHA" | head --bytes=7)
        # Looks like this: b2018.12.06-a76a52f
        tag="b$(date +%Y.%m.%d)-${short_sha}"
        docker tag "$image_name" "$image_name:$tag"
        docker push "$image_name"
        docker push "$image_name:$tag"
      fi

  - id: "Start radicle-server and IPFS daemon"
    name: 'docker/compose:1.23.2'
    waitFor:
    - "Build radicle-server image"
    entrypoint: sh
    args:
    - "-c"
    - |
      set -euxo pipefail
      docker-compose -f test/docker-compose.yaml up -d postgres
      sleep 5 # Wait for the DB to be ready
      docker-compose -f test/docker-compose.yaml up -d
      sleep 3 # Wait for service to be booted

      # Connect services to 'cloudbuild' network so they can be
      # accessed by other steps
      docker network connect cloudbuild test_radicle-server_1 --alias radicle-server
      docker network connect cloudbuild test_ipfs-test-network_1 --alias ipfs-test-network

      # Add the empty entry to the IPFS test network. Radicle requires it
      echo '{"radicle": true}' | docker exec -i test_ipfs-test-network_1 ipfs dag put --pin

  - id: "Integration tests"
    waitFor:
    - "Start radicle-server and IPFS daemon"
    name: 'haskell:8.6.3'
    env: ['STACK_ROOT=/workspace/.stack']
    entrypoint: 'bash'
    args:
    - "-c"
    - |
      set -euxo pipefail

      export RAD_IPFS_API_URL=http://ipfs-test-network:5001
      export RADPATH="$(pwd)/rad"

      stack exec -- radicle-daemon &

      stack test :e2e
      stack exec -- radicle test/machine-backends.rad radicle-server
