name: radicle
version: '0.0.0'
author: Monadic <team@monadic.xyz>
maintainer: Monadic <team@monadic.xyz>
license: MIT
git: oscoin/radicle
extra-source-files:
- README.md
- ChangeLog.md
- bin/*

build-type: Custom

custom-setup:
  dependencies:
    - base >= 4 && <5
    - Cabal
    - filepath
    - directory

dependencies:
- base >=4 && <5
- protolude

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

data-files:
- rad/**/*.rad

library:
  source-dirs: src
  dependencies:
  - aeson
  - ansi-terminal
  - bytestring
  - conduit
  - conduit-extra
  - containers
  - cryptonite
  - directory
  - filepath
  - generics-eot
  - haskeline
  - http-client
  - http-conduit
  - http-types
  - http-media
  - ipld-cid
  - megaparsec
  - mtl
  - multibase
  - optparse-applicative
  - pointed
  - prettyprinter
  - prettyprinter-ansi-terminal
  - process
  - resourcet
  - safe-exceptions
  - scientific
  - serialise
  - servant
  - servant-client
  - servant-swagger
  - swagger2
  - template-haskell
  - text
  - time
  - unliftio-core
  - unliftio
  - unordered-containers
  - uuid
  - vector

tests:
  spec:
    main: Main.hs
    source-dirs:
    - test/spec
    dependencies:
    - radicle
    - async
    - containers
    - cryptonite
    - directory
    - filemanip
    - interpolate
    - megaparsec
    - process
    - QuickCheck
    - quickcheck-instances
    - scientific
    - serialise
    - stm
    - string-qq
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - text
    - time
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
  doctest:
    main: Main.hs
    source-dirs:
    - test/docs
    dependencies:
    - doctest
    - Glob
    - hpack
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
  e2e:
    main: Main.hs
    source-dirs:
    - test/e2e
    dependencies:
    - process
    - directory
    - filepath
    # Requires the 'git-remote-ipfs' executable
    - git-remote-ipfs
    - safe-exceptions
    - tasty
    - tasty-discover
    - tasty-hunit
    - temporary
    - text
    - unliftio

executables:
  rad:
    main: Rad.hs
    source-dirs: exe
    other-modules: [Paths_radicle]
    dependencies:
    - directory
    - filepath
    - text
    - unix
    ghc-options: -main-is Rad -O3 -threaded

  radicle:
    main: RadicleExe.hs
    source-dirs: exe
    other-modules: []
    dependencies:
    - radicle
    - bytestring
    - directory
    - optparse-applicative
    ghc-options: -main-is RadicleExe

  rad-daemon-radicle:
    main: Daemon.hs
    source-dirs: exe
    other-modules: []
    dependencies:
    - containers
    - mtl
    - radicle
    - safe-exceptions
    - servant-server
    - text
    - time
    - unliftio
    - warp
    ghc-options: -main-is Daemon

  radicle-doc:
    main: Doc.hs
    source-dirs: exe/
    other-modules: []
    dependencies:
    - radicle
    - optparse-applicative
    - pandoc
    - text
    ghc-options: -main-is Doc

  radicle-ref-doc:
    main: ReferenceDoc.hs
    source-dirs: exe/
    other-modules: []
    dependencies:
    - radicle
    - pandoc
    - data-default
    - containers
    - text
    - yaml
    ghc-options: -main-is ReferenceDoc

  radicle-github-issues:
    main: GithubIssues.hs
    source-dirs: exe/
    other-modules: []
    dependencies:
    - radicle
    - containers
    - time
    - github
    - optparse-applicative
    ghc-options: -main-is GithubIssues

  radicle-benchmark:
    main: Benchmarks.hs
    source-dirs: exe/
    other-modules: []
    dependencies:
    - radicle
    - criterion
    ghc-options: -main-is Benchmarks

  rad-machines:
    main: Machines.hs
    source-dirs: exe/
    other-modules: []
    dependencies:
    - radicle
    - optparse-applicative
    - safe-exceptions
    ghc-options: -main-is Machines

default-extensions:
- AutoDeriveTypeable
- ApplicativeDo
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeOperators
- ViewPatterns
