name: radicle
version: '0.0.4'
author: Monadic <team@monadic.xyz>
maintainer: Monadic <team@monadic.xyz>
license: MIT
git: oscoin/radicle
extra-source-files:
- README.md
- ChangeLog.md
- bin/*

build-type: Custom

custom-setup:
  dependencies:
    - base >= 4 && <5
    - Cabal
    - filepath
    - directory

dependencies:
- base >=4 && <5
- protolude

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

data-files:
- rad/**/*.rad

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - clock
  - conduit
  - conduit-extra
  - containers
  - directory
  - filepath
  - http-client
  - http-conduit
  - http-types
  - http-media
  - ipld-cid
  - mtl
  - multibase
  - optparse-applicative
  - radicle-lang
  - radicle-repl
  - resourcet
  - retry
  - safe-exceptions
  - servant
  - servant-client
  - servant-swagger
  - swagger2
  - text
  - time
  - unliftio-core
  - unliftio
  - unordered-containers

tests:
  spec:
    main: Main.hs
    source-dirs:
    - test/spec
    dependencies:
    - async
    - radicle
    - stm
    - tasty
    - tasty-hunit
    build-tools:
    - tasty-discover
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
  doctest:
    main: Main.hs
    source-dirs:
    - test/docs
    dependencies:
    - doctest
    - Glob
    - hpack
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
  e2e:
    main: Main.hs
    source-dirs:
    - test/e2e
    dependencies:
    - process
    - directory
    - exceptions
    - filepath
    # Requires the 'git-remote-ipfs' executable
    - git-remote-ipfs
    - safe-exceptions
    - tasty
    - tasty-hunit
    - temporary
    - text
    - unliftio
    build-tools:
    - tasty-discover

executables:
  rad:
    main: Rad.hs
    source-dirs: exe
    other-modules: [Paths_radicle]
    dependencies:
    - directory
    - filepath
    - text
    - unix
    ghc-options: ["-main-is", "Rad", "-O3", "-threaded"]

  radicle:
    main: RadicleExe.hs
    source-dirs: exe
    other-modules: []
    dependencies:
    - radicle
    - radicle-repl
    - bytestring
    - directory
    - optparse-applicative
    ghc-options: ["-main-is", "RadicleExe"]

  rad-daemon-radicle:
    main: Daemon.hs
    source-dirs: exe
    other-modules: []
    dependencies:
    - containers
    - mtl
    - radicle
    - radicle-lang
    - safe-exceptions
    - servant-server
    - text
    - time
    - unliftio
    - wai-cors
    - warp
    ghc-options: ["-main-is", "Daemon"]

  rad-repl:
    main: RadicleRepl.hs
    source-dirs: exe
    other-modules: []
    dependencies:
    - radicle
    - radicle-repl
    - optparse-applicative
    ghc-options: ["-main-is", "RadicleRepl"]

  radicle-doc:
    main: Doc.hs
    source-dirs: exe/
    other-modules: []
    dependencies:
    - radicle
    - radicle-lang
    - optparse-applicative
    - pandoc
    - text
    ghc-options: ["-main-is", "Doc"]

  radicle-ref-doc:
    main: ReferenceDoc.hs
    source-dirs: exe/
    other-modules: []
    dependencies:
    - radicle
    - radicle-lang
    - radicle-repl
    - pandoc
    - data-default
    - containers
    - text
    - yaml
    ghc-options: ["-main-is", "ReferenceDoc"]

  radicle-github-issues:
    main: GithubIssues.hs
    source-dirs: exe/
    other-modules: []
    dependencies:
    - containers
    - github < 0.21
    - optparse-applicative
    - radicle-lang
    - time
    ghc-options: ["-main-is", "GithubIssues"]

  radicle-benchmark:
    main: Benchmarks.hs
    source-dirs: exe/
    other-modules: []
    dependencies:
    - radicle-lang
    - criterion
    ghc-options: ["-main-is", "Benchmarks"]

  rad-machines:
    main: Machines.hs
    source-dirs: exe/
    other-modules: []
    dependencies:
    - radicle
    - optparse-applicative
    - safe-exceptions
    ghc-options: ["-main-is", "Machines"]

default-extensions:
- AutoDeriveTypeable
- ApplicativeDo
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeOperators
- ViewPatterns
