#!/usr/bin/env bash

FILE="$(mktemp)"
cat << SRC > $FILE
(load! "rad/monadic/issues.rad")
(def iss-map (apply dict (map (seq (list-issues)))
(print! (fzf-select-by-key! (map-keys show (list-issues))))
SRC
stack exec --silent radicle -- $FILE

