#!/usr/bin/env bash

TEMPLATE="$(mktemp)"
cat << SRC > $TEMPLATE
{:title      "Pick a title"
 :body       "Pick a body"
 :labels     []
 :state      :open
 :comments   []
 :created-at (now!)}
SRC

SRC_FILE="$(mktemp)"
cat << SRC > $SRC_FILE
(load! "rad/monadic/issues.rad")
(create-issue!
  $(cat $TEMPLATE | vipe))
SRC
radicle $SRC_FILE

